apiVersion: v1
kind: Pod
metadata:
  name: mydb
spec:
  containers:
  - name: mydb
    image: mysql
    env:
      - name: MYSQL_ROOT_PASSWORD
        value: abc123
      - name: MYSQL_DATABASE
        value: 2day
