apiVersion: v1
kind: PersistentVolume
metadata:
  name: mypv2
  labels:
    type: local-500Mi
spec:
  capacity:
    storage: 500Mi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /vol2
    type: DirectoryOrCreate