apiVersion: v1
kind: PersistentVolume
metadata:
  name: mypv1
  labels:
    type: local-1Gi
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /vol1
    type: DirectoryOrCreate