apiVersion: v1
kind: PersistentVolume
metadata:
  name: mynfspv
  labels:
    name : mypv
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteMany
  nfs:
    path: /nfsdata
    server: 192.168.11.20
