apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mynfspvc
spec:
  resources:
    requests:
      storage: 100Mi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  selector:
    matchLabels:
      name:  mypv
