apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: myrs
spec:
  replicas: 2
  selector:
    matchLabels:
      apps: nginx-rs
  template:
    metadata:
      labels:
        apps: nginx-rs
    spec:
      containers:
        - name: sleepy
          image: nginx
