apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-test
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx-testbed
  template:
    metadata:
      labels:
        app: nginx-testbed
    spec:
      containers:
      - name: www
        image: nginx:1.17
        ports:
        - containerPort: 80
          protocol: TCP

---
kind: Service
apiVersion: v1
metadata:
  name: web-test-lb
spec:
  selector:
    app: nginx-testbed 
  type:  LoadBalancer 
  ports:
  - port:  80
    targetPort:  80
    protocol : TCP